### ISSUE TITLE
About the markdown panel.

### ISSUE THREAD

**Issue by huixu007** [bvn13/SpringBlog#4]
Hello, 
I have a problem. I can't display the markdown preview normally when the article is edited. Do you have a solution?
![img](https://s1.ax1x.com/2018/01/14/pNPxDs.png)

**Comment by bvn13** [comment]
Hi. As all js-libs working with mqrkdown were disabled, there is only one way to have a preview now - save the draft and open your article.

But I could implement only preview if neccessary.

**Comment by huixu007** [comment]
Thank you for answering me.

**Comment by bvn13** [comment]
@huxuying I have implemented live preview. Please check out new release: SpringBlog-v2.8.2 (or last commit)
